import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// import "./tabler-icons/table-icons.css";
import Link from "next/link";
import React from "react";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Quran | Dashboard</title>

        {/* Meta SEO */}
        <meta
          name="title"
          content="Quran | Dashboard"
        />


        <link rel="icon" type="image/png" sizes="16x16" href="/favicon.png"/>
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />

      </head>
      <body className={inter.className}>
        {children}
        {footer()}
      </body>
    </html>
  );

  function footer() {
    return (
      <footer className="bg-white dark:bg-gray-800 p-6">
        <div className="text-start">
          <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-4">Developer</h3>
          <ul className="text-gray-500 dark:text-gray-400 mb-6">
            <li>
              <Link href="https://github.com/DimzsArdiminda/quran-me" className="hover:underline">Source Code</Link>
            </li>
            <li>
              <Link href="https://equran.id/apidev/v2" className="hover:underline">API</Link>
            </li>
          </ul>
          <div className="text-center text-sm text-gray-500 dark:text-gray-400">
            © {new Date().getFullYear()} All rights reserved.
          </div>
          <div className="flex justify-center mt-5 space-x-5">
            <p>Contact Me:</p>
            <Link href="https://www.instagram.com/penggalan.reformasi_/" className="text-gray-500 hover:text-gray-900 dark:hover:text-white dark:text-gray-400">
              Instagram
            </Link>
          </div>
        </div>
      </footer>
    );
  }
}
